/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL },
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if (code >=0 && (size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if (code >=0 && (size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_XmmsClientInterface(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_XmmsClientInterface(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_XmmsClientInterface(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


 /* Includes the header in the wrapper code */
 #include "xmmsc/xmmsc_idnumbers.h"
 #include "xmmsclient/xmmsclient.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_query_attribute_t_key_set(void * jarg1, char * jarg2) {
  xmmsc_query_attribute_t *arg1 = (xmmsc_query_attribute_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (xmmsc_query_attribute_t *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg1->key) free((char *)arg1->key);
    if (arg2) {
      arg1->key = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->key, (const char *)arg2);
    } else {
      arg1->key = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_query_attribute_t_key_get(void * jarg1) {
  char * jresult ;
  xmmsc_query_attribute_t *arg1 = (xmmsc_query_attribute_t *) 0 ;
  char *result = 0 ;
  
  arg1 = (xmmsc_query_attribute_t *)jarg1; 
  result = (char *) ((arg1)->key);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_query_attribute_t_value_set(void * jarg1, char * jarg2) {
  xmmsc_query_attribute_t *arg1 = (xmmsc_query_attribute_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (xmmsc_query_attribute_t *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg1->value) free((char *)arg1->value);
    if (arg2) {
      arg1->value = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->value, (const char *)arg2);
    } else {
      arg1->value = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_query_attribute_t_value_get(void * jarg1) {
  char * jresult ;
  xmmsc_query_attribute_t *arg1 = (xmmsc_query_attribute_t *) 0 ;
  char *result = 0 ;
  
  arg1 = (xmmsc_query_attribute_t *)jarg1; 
  result = (char *) ((arg1)->value);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_xmmsc_query_attribute_t() {
  void * jresult ;
  xmmsc_query_attribute_t *result = 0 ;
  
  result = (xmmsc_query_attribute_t *)(xmmsc_query_attribute_t *) calloc(1, sizeof(xmmsc_query_attribute_t));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_xmmsc_query_attribute_t(void * jarg1) {
  xmmsc_query_attribute_t *arg1 = (xmmsc_query_attribute_t *) 0 ;
  
  arg1 = (xmmsc_query_attribute_t *)jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_init(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  xmmsc_connection_t *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (xmmsc_connection_t *)xmmsc_init((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_connect(void * jarg1, char * jarg2) {
  int jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)xmmsc_connect(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_unref(void * jarg1) {
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  xmmsc_unref(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_lock_set(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  void *arg2 = (void *) 0 ;
  void (*arg3)(void *) = (void (*)(void *)) 0 ;
  void (*arg4)(void *) = (void (*)(void *)) 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (void *)jarg2; 
  arg3 = (void (*)(void *))jarg3; 
  arg4 = (void (*)(void *))jarg4; 
  xmmsc_lock_set(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_disconnect_callback_set(void * jarg1, void * jarg2, void * jarg3) {
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  void (*arg2)(void *) = (void (*)(void *)) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (void (*)(void *))jarg2; 
  arg3 = (void *)jarg3; 
  xmmsc_disconnect_callback_set(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_io_need_out_callback_set(void * jarg1, void * jarg2, void * jarg3) {
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  void (*arg2)(int,void *) = (void (*)(int,void *)) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (void (*)(int,void *))jarg2; 
  arg3 = (void *)jarg3; 
  xmmsc_io_need_out_callback_set(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_io_disconnect(void * jarg1) {
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  xmmsc_io_disconnect(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_io_want_out(void * jarg1) {
  int jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (int)xmmsc_io_want_out(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_io_out_handle(void * jarg1) {
  int jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (int)xmmsc_io_out_handle(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_io_in_handle(void * jarg1) {
  int jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (int)xmmsc_io_in_handle(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_io_fd_get(void * jarg1) {
  int jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (int)xmmsc_io_fd_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_get_last_error(void * jarg1) {
  char * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (char *)xmmsc_get_last_error(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_entry_format(char * jarg1, int jarg2, char * jarg3, void * jarg4) {
  int jresult ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *arg4 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (char *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (xmmsc_result_t *)jarg4; 
  result = (int)xmmsc_entry_format(arg1,arg2,(char const *)arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_quit(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_quit(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_plugin_list(void * jarg1, int jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmms_plugin_type_t arg2 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (xmms_plugin_type_t)jarg2; 
  result = (xmmsc_result_t *)xmmsc_plugin_list(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_main_stats(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_main_stats(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_quit(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_quit(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_querygen_and(void * jarg1, unsigned int jarg2) {
  char * jresult ;
  xmmsc_query_attribute_t *arg1 = (xmmsc_query_attribute_t *) 0 ;
  unsigned int arg2 ;
  char *result = 0 ;
  
  arg1 = (xmmsc_query_attribute_t *)jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (char *)xmmsc_querygen_and(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_sqlite_prepare_string(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (char *)xmmsc_sqlite_prepare_string((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_shuffle(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playlist_shuffle(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_add(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playlist_add(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_add_args(void * jarg1, char * jarg2, int jarg3, void * jarg4) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  char **arg4 = (char **) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (char **)jarg4; 
  result = (xmmsc_result_t *)xmmsc_playlist_add_args(arg1,(char const *)arg2,arg3,(char const **)arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_add_id(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_playlist_add_id(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_add_encoded(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playlist_add_encoded(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_remove(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_playlist_remove(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_clear(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playlist_clear(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_list(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playlist_list(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_sort(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playlist_sort(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_set_next(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_playlist_set_next(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_set_next_rel(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  int32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (int32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_playlist_set_next_rel(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_move(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  uint32_t arg3 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  uint32_t *argp3 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  argp3 = (uint32_t *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (xmmsc_result_t *)xmmsc_playlist_move(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_current_pos(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playlist_current_pos(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_insert(void * jarg1, int jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_playlist_insert(arg1,arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_insert_args(void * jarg1, int jarg2, char * jarg3, int jarg4, void * jarg5) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  char **arg5 = (char **) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (char **)jarg5; 
  result = (xmmsc_result_t *)xmmsc_playlist_insert_args(arg1,arg2,(char const *)arg3,arg4,(char const **)arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_insert_encoded(void * jarg1, int jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_playlist_insert_encoded(arg1,arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_insert_id(void * jarg1, int jarg2, void * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int arg2 ;
  uint32_t arg3 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp3 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (int)jarg2; 
  argp3 = (uint32_t *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (xmmsc_result_t *)xmmsc_playlist_insert_id(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_radd(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playlist_radd(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playlist_radd_encoded(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playlist_radd_encoded(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_playlist_changed(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_playlist_changed(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_playlist_current_pos(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_playlist_current_pos(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_stop(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_stop(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_tickle(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_tickle(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_start(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_start(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_pause(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_pause(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_current_id(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_current_id(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_seek_ms(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_playback_seek_ms(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_seek_ms_rel(void * jarg1, int jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int arg2 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (int)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playback_seek_ms_rel(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_seek_samples(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_playback_seek_samples(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_seek_samples_rel(void * jarg1, int jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  int arg2 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (int)jarg2; 
  result = (xmmsc_result_t *)xmmsc_playback_seek_samples_rel(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_playtime(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_playtime(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_status(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_status(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_volume_set(void * jarg1, char * jarg2, void * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t arg3 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp3 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  argp3 = (uint32_t *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (xmmsc_result_t *)xmmsc_playback_volume_set(arg1,(char const *)arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_playback_volume_get(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_playback_volume_get(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_playback_volume_changed(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_playback_volume_changed(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_playback_status(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_playback_status(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_playback_current_id(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_playback_current_id(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_signal_playback_playtime(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_signal_playback_playtime(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_configval_set(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_configval_set(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_configval_list(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_configval_list(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_configval_get(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_configval_get(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_configval_register(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_configval_register(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_configval_changed(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_configval_changed(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_mediainfo_reader_status(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_mediainfo_reader_status(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_signal_visualisation_data(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_signal_visualisation_data(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_signal_mediainfo_reader_unindexed(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_signal_mediainfo_reader_unindexed(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_userconfdir_get(char * jarg1, int jarg2) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)xmmsc_userconfdir_get(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_select(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_select(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlist_save_current(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlist_save_current(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlist_load(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlist_load(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_add_entry(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_add_entry(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_add_entry_args(void * jarg1, char * jarg2, int jarg3, void * jarg4) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  char **arg4 = (char **) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (char **)jarg4; 
  result = (xmmsc_result_t *)xmmsc_medialib_add_entry_args(arg1,(char const *)arg2,arg3,(char const **)arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_add_entry_encoded(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_add_entry_encoded(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_get_info(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_medialib_get_info(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_add_to_playlist(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_add_to_playlist(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlists_list(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlists_list(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlist_list(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlist_list(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlist_import(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlist_import(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlist_export(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlist_export(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_playlist_remove(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_playlist_remove(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_path_import(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_path_import(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_path_import_encoded(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_path_import_encoded(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_rehash(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_medialib_rehash(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_get_id(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_medialib_get_id(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_remove_entry(void * jarg1, void * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (xmmsc_result_t *)xmmsc_medialib_remove_entry(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_entry_property_set_int(void * jarg1, void * jarg2, char * jarg3, void * jarg4) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  int32_t arg4 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  int32_t *argp4 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (char *)jarg3; 
  argp4 = (int32_t *)jarg4; 
  if (!argp4) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_t", 0);
    return 0;
  }
  arg4 = *argp4; 
  result = (xmmsc_result_t *)xmmsc_medialib_entry_property_set_int(arg1,arg2,(char const *)arg3,arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_entry_property_set_int_with_source(void * jarg1, void * jarg2, char * jarg3, char * jarg4, void * jarg5) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int32_t arg5 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  int32_t *argp5 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (char *)jarg3; 
  arg4 = (char *)jarg4; 
  argp5 = (int32_t *)jarg5; 
  if (!argp5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_t", 0);
    return 0;
  }
  arg5 = *argp5; 
  result = (xmmsc_result_t *)xmmsc_medialib_entry_property_set_int_with_source(arg1,arg2,(char const *)arg3,(char const *)arg4,arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_entry_property_set_str(void * jarg1, void * jarg2, char * jarg3, char * jarg4) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (char *)jarg3; 
  arg4 = (char *)jarg4; 
  result = (xmmsc_result_t *)xmmsc_medialib_entry_property_set_str(arg1,arg2,(char const *)arg3,(char const *)arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_entry_property_set_str_with_source(void * jarg1, void * jarg2, char * jarg3, char * jarg4, char * jarg5) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  char *arg5 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (char *)jarg3; 
  arg4 = (char *)jarg4; 
  arg5 = (char *)jarg5; 
  result = (xmmsc_result_t *)xmmsc_medialib_entry_property_set_str_with_source(arg1,arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_entry_property_remove(void * jarg1, void * jarg2, char * jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (char *)jarg3; 
  result = (xmmsc_result_t *)xmmsc_medialib_entry_property_remove(arg1,arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_medialib_entry_property_remove_with_source(void * jarg1, void * jarg2, char * jarg3, char * jarg4) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  uint32_t *argp2 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (char *)jarg3; 
  arg4 = (char *)jarg4; 
  result = (xmmsc_result_t *)xmmsc_medialib_entry_property_remove_with_source(arg1,arg2,(char const *)arg3,(char const *)arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_xform_media_browse(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_xform_media_browse(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_xform_media_browse_encoded(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_xform_media_browse_encoded(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_bindata_add(void * jarg1, void * jarg2, unsigned int jarg3) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned int arg3 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (unsigned char *)jarg2; 
  arg3 = (unsigned int)jarg3; 
  result = (xmmsc_result_t *)xmmsc_bindata_add(arg1,(unsigned char const *)arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_bindata_retrieve(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_bindata_retrieve(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_bindata_remove(void * jarg1, char * jarg2) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_t *)xmmsc_bindata_remove(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_medialib_entry_changed(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_medialib_entry_changed(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_medialib_entry_added(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_medialib_entry_added(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_broadcast_medialib_playlist_loaded(void * jarg1) {
  void * jresult ;
  xmmsc_connection_t *arg1 = (xmmsc_connection_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_connection_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_broadcast_medialib_playlist_loaded(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_xmmsc_result_restart(void * jarg1) {
  void * jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  xmmsc_result_t *result = 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (xmmsc_result_t *)xmmsc_result_restart(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_run(void * jarg1, void * jarg2) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  xmms_ipc_msg_t *arg2 = (xmms_ipc_msg_t *) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (xmms_ipc_msg_t *)jarg2; 
  xmmsc_result_run(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_class(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  xmmsc_result_type_t result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (xmmsc_result_type_t)xmmsc_result_get_class(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_disconnect(void * jarg1) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  xmmsc_result_disconnect(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_ref(void * jarg1) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  xmmsc_result_ref(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_unref(void * jarg1) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  xmmsc_result_unref(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_notifier_set(void * jarg1, void * jarg2, void * jarg3) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  xmmsc_result_notifier_t arg2 = (xmmsc_result_notifier_t) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (xmmsc_result_notifier_t)jarg2; 
  arg3 = (void *)jarg3; 
  xmmsc_result_notifier_set(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_wait(void * jarg1) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  xmmsc_result_wait(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_iserror(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (int)xmmsc_result_iserror(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_result_get_error(void * jarg1) {
  char * jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char *result = 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (char *)xmmsc_result_get_error(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_int(void * jarg1, void * jarg2) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int *arg2 = (int *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (int *)jarg2; 
  result = (int)xmmsc_result_get_int(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_uint(void * jarg1, void * jarg2) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (uint32_t *)jarg2; 
  result = (int)xmmsc_result_get_uint(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_string(void * jarg1, void * jarg2) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char **)jarg2; 
  result = (int)xmmsc_result_get_string(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_bin(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  unsigned char **arg2 = (unsigned char **) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (unsigned char **)jarg2; 
  arg3 = (unsigned int *)jarg3; 
  result = (int)xmmsc_result_get_bin(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_dict_entry_type(void * jarg1, char * jarg2) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char *arg2 = (char *) 0 ;
  xmmsc_result_value_type_t result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (xmmsc_result_value_type_t)xmmsc_result_get_dict_entry_type(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_dict_entry_str(void * jarg1, char * jarg2, void * jarg3) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char **arg3 = (char **) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char **)jarg3; 
  result = (int)xmmsc_result_get_dict_entry_str(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_dict_entry_int32(void * jarg1, char * jarg2, void * jarg3) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int32_t *arg3 = (int32_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int32_t *)jarg3; 
  result = (int)xmmsc_result_get_dict_entry_int32(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_dict_entry_uint32(void * jarg1, char * jarg2, void * jarg3) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t *arg3 = (uint32_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (uint32_t *)jarg3; 
  result = (int)xmmsc_result_get_dict_entry_uint32(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_dict_foreach(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  xmmsc_dict_foreach_func arg2 = (xmmsc_dict_foreach_func) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (xmmsc_dict_foreach_func)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)xmmsc_result_dict_foreach(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_propdict_foreach(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  xmmsc_propdict_foreach_func arg2 = (xmmsc_propdict_foreach_func) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (xmmsc_propdict_foreach_func)jarg2; 
  arg3 = (void *)jarg3; 
  result = (int)xmmsc_result_propdict_foreach(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_xmmsc_result_source_preference_set(void * jarg1, void * jarg2) {
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char **arg2 = (char **) 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char **)jarg2; 
  xmmsc_result_source_preference_set(arg1,(char const **)arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_is_list(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (int)xmmsc_result_is_list(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_list_next(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (int)xmmsc_result_list_next(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_list_first(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (int)xmmsc_result_list_first(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_list_valid(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (int)xmmsc_result_list_valid(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_xmmsc_result_get_type(void * jarg1) {
  int jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  int result;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  result = (int)xmmsc_result_get_type(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_xmmsc_result_decode_url(void * jarg1, char * jarg2) {
  char * jresult ;
  xmmsc_result_t *arg1 = (xmmsc_result_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (xmmsc_result_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (char *)xmmsc_result_decode_url(arg1,(char const *)arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

