/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum xmms_object_cmd_arg_type_t {
  XMMS_OBJECT_CMD_ARG_NONE,
  XMMS_OBJECT_CMD_ARG_UINT32,
  XMMS_OBJECT_CMD_ARG_INT32,
  XMMS_OBJECT_CMD_ARG_STRING,
  XMMS_OBJECT_CMD_ARG_DICT,
  XMMS_OBJECT_CMD_ARG_LIST,
  XMMS_OBJECT_CMD_ARG_PROPDICT,
  XMMS_OBJECT_CMD_ARG_BIN
}
