/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum xmms_ipc_objects_t {
  XMMS_IPC_OBJECT_MAIN,
  XMMS_IPC_OBJECT_PLAYLIST,
  XMMS_IPC_OBJECT_CONFIG,
  XMMS_IPC_OBJECT_OUTPUT,
  XMMS_IPC_OBJECT_MEDIALIB,
  XMMS_IPC_OBJECT_SIGNAL,
  XMMS_IPC_OBJECT_VISUALISATION,
  XMMS_IPC_OBJECT_MEDIAINFO_READER,
  XMMS_IPC_OBJECT_XFORM,
  XMMS_IPC_OBJECT_BINDATA,
  XMMS_IPC_OBJECT_END
}
