/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum xmms_mediainfo_reader_status_t {
  XMMS_MEDIAINFO_READER_STATUS_IDLE,
  XMMS_MEDIAINFO_READER_STATUS_RUNNING
}
