/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum xmms_playlist_changed_actions_t {
  XMMS_PLAYLIST_CHANGED_ADD,
  XMMS_PLAYLIST_CHANGED_INSERT,
  XMMS_PLAYLIST_CHANGED_SHUFFLE,
  XMMS_PLAYLIST_CHANGED_REMOVE,
  XMMS_PLAYLIST_CHANGED_CLEAR,
  XMMS_PLAYLIST_CHANGED_MOVE,
  XMMS_PLAYLIST_CHANGED_SORT
}
