/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class xmmsc_query_attribute_t : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal xmmsc_query_attribute_t(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(xmmsc_query_attribute_t obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~xmmsc_query_attribute_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        XmmsClientInterfacePINVOKE.delete_xmmsc_query_attribute_t(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public string key {
    set {
      XmmsClientInterfacePINVOKE.xmmsc_query_attribute_t_key_set(swigCPtr, value);
    } 
    get {
      string ret = XmmsClientInterfacePINVOKE.xmmsc_query_attribute_t_key_get(swigCPtr);
      return ret;
    } 
  }

  public string value {
    set {
      XmmsClientInterfacePINVOKE.xmmsc_query_attribute_t_value_set(swigCPtr, value);
    } 
    get {
      string ret = XmmsClientInterfacePINVOKE.xmmsc_query_attribute_t_value_get(swigCPtr);
      return ret;
    } 
  }

  public xmmsc_query_attribute_t() : this(XmmsClientInterfacePINVOKE.new_xmmsc_query_attribute_t(), true) {
  }

}
