/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class XmmsClientInterface {
  public static SWIGTYPE_p_xmmsc_connection_St xmmsc_init(string clientname) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_init(clientname);
    SWIGTYPE_p_xmmsc_connection_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_connection_St(cPtr, false);
    return ret;
  }

  public static int xmmsc_connect(SWIGTYPE_p_xmmsc_connection_St arg0, string arg1) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_connect(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0), arg1);
    return ret;
  }

  public static void xmmsc_unref(SWIGTYPE_p_xmmsc_connection_St c) {
    XmmsClientInterfacePINVOKE.xmmsc_unref(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
  }

  public static void xmmsc_lock_set(SWIGTYPE_p_xmmsc_connection_St conn, SWIGTYPE_p_void arg1, SWIGTYPE_p_f_p_void__void lockfunc, SWIGTYPE_p_f_p_void__void unlockfunc) {
    XmmsClientInterfacePINVOKE.xmmsc_lock_set(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), SWIGTYPE_p_void.getCPtr(arg1), SWIGTYPE_p_f_p_void__void.getCPtr(lockfunc), SWIGTYPE_p_f_p_void__void.getCPtr(unlockfunc));
  }

  public static void xmmsc_disconnect_callback_set(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_f_p_void__void callback, SWIGTYPE_p_void userdata) {
    XmmsClientInterfacePINVOKE.xmmsc_disconnect_callback_set(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_f_p_void__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static void xmmsc_io_need_out_callback_set(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_f_int_p_void__void callback, SWIGTYPE_p_void userdata) {
    XmmsClientInterfacePINVOKE.xmmsc_io_need_out_callback_set(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_f_int_p_void__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static void xmmsc_io_disconnect(SWIGTYPE_p_xmmsc_connection_St c) {
    XmmsClientInterfacePINVOKE.xmmsc_io_disconnect(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
  }

  public static int xmmsc_io_want_out(SWIGTYPE_p_xmmsc_connection_St c) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_io_want_out(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    return ret;
  }

  public static int xmmsc_io_out_handle(SWIGTYPE_p_xmmsc_connection_St c) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_io_out_handle(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    return ret;
  }

  public static int xmmsc_io_in_handle(SWIGTYPE_p_xmmsc_connection_St c) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_io_in_handle(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    return ret;
  }

  public static int xmmsc_io_fd_get(SWIGTYPE_p_xmmsc_connection_St c) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_io_fd_get(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    return ret;
  }

  public static string xmmsc_get_last_error(SWIGTYPE_p_xmmsc_connection_St c) {
    string ret = XmmsClientInterfacePINVOKE.xmmsc_get_last_error(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    return ret;
  }

  public static int xmmsc_entry_format(string target, int len, string fmt, SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_entry_format(target, len, fmt, SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_quit(SWIGTYPE_p_xmmsc_connection_St arg0) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_quit(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_plugin_list(SWIGTYPE_p_xmmsc_connection_St c, xmms_plugin_type_t type) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_plugin_list(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), (int)type);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_main_stats(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_main_stats(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_quit(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_quit(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static string xmmsc_querygen_and(xmmsc_query_attribute_t attributes, uint n) {
    string ret = XmmsClientInterfacePINVOKE.xmmsc_querygen_and(xmmsc_query_attribute_t.getCPtr(attributes), n);
    return ret;
  }

  public static string xmmsc_sqlite_prepare_string(string input) {
    string ret = XmmsClientInterfacePINVOKE.xmmsc_sqlite_prepare_string(input);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_shuffle(SWIGTYPE_p_xmmsc_connection_St arg0) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_shuffle(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_add(SWIGTYPE_p_xmmsc_connection_St arg0, string arg1) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_add(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0), arg1);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_add_args(SWIGTYPE_p_xmmsc_connection_St arg0, string arg1, int arg2, SWIGTYPE_p_p_char arg3) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_add_args(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0), arg1, arg2, SWIGTYPE_p_p_char.getCPtr(arg3));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_add_id(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_add_id(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_add_encoded(SWIGTYPE_p_xmmsc_connection_St c, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_add_encoded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_remove(SWIGTYPE_p_xmmsc_connection_St arg0, SWIGTYPE_p_uint32_t arg1) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_remove(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0), SWIGTYPE_p_uint32_t.getCPtr(arg1));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_clear(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_clear(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_list(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_list(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_sort(SWIGTYPE_p_xmmsc_connection_St c, string arg1) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_sort(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), arg1);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_set_next(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t arg1) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_set_next(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(arg1));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_set_next_rel(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_int32_t arg1) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_set_next_rel(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_int32_t.getCPtr(arg1));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_move(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t arg1, SWIGTYPE_p_uint32_t arg2) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_move(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(arg1), SWIGTYPE_p_uint32_t.getCPtr(arg2));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_current_pos(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_current_pos(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_insert(SWIGTYPE_p_xmmsc_connection_St c, int pos, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_insert(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), pos, url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_insert_args(SWIGTYPE_p_xmmsc_connection_St c, int pos, string url, int numargs, SWIGTYPE_p_p_char args) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_insert_args(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), pos, url, numargs, SWIGTYPE_p_p_char.getCPtr(args));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_insert_encoded(SWIGTYPE_p_xmmsc_connection_St c, int pos, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_insert_encoded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), pos, url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_insert_id(SWIGTYPE_p_xmmsc_connection_St c, int pos, SWIGTYPE_p_uint32_t id) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_insert_id(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), pos, SWIGTYPE_p_uint32_t.getCPtr(id));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_radd(SWIGTYPE_p_xmmsc_connection_St c, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_radd(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playlist_radd_encoded(SWIGTYPE_p_xmmsc_connection_St c, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playlist_radd_encoded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_playlist_changed(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_playlist_changed(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_playlist_current_pos(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_playlist_current_pos(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_stop(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_stop(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_tickle(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_tickle(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_start(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_start(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_pause(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_pause(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_current_id(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_current_id(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_seek_ms(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t milliseconds) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_seek_ms(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(milliseconds));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_seek_ms_rel(SWIGTYPE_p_xmmsc_connection_St c, int milliseconds) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_seek_ms_rel(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), milliseconds);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_seek_samples(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t samples) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_seek_samples(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(samples));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_seek_samples_rel(SWIGTYPE_p_xmmsc_connection_St c, int samples) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_seek_samples_rel(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), samples);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_playtime(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_playtime(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_status(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_status(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_volume_set(SWIGTYPE_p_xmmsc_connection_St c, string channel, SWIGTYPE_p_uint32_t volume) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_volume_set(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), channel, SWIGTYPE_p_uint32_t.getCPtr(volume));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_playback_volume_get(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_playback_volume_get(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_playback_volume_changed(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_playback_volume_changed(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_playback_status(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_playback_status(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_playback_current_id(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_playback_current_id(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_signal_playback_playtime(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_signal_playback_playtime(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_configval_set(SWIGTYPE_p_xmmsc_connection_St c, string key, string val) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_configval_set(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), key, val);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_configval_list(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_configval_list(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_configval_get(SWIGTYPE_p_xmmsc_connection_St c, string key) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_configval_get(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), key);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_configval_register(SWIGTYPE_p_xmmsc_connection_St c, string valuename, string defaultvalue) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_configval_register(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), valuename, defaultvalue);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_configval_changed(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_configval_changed(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_mediainfo_reader_status(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_mediainfo_reader_status(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_signal_visualisation_data(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_signal_visualisation_data(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_signal_mediainfo_reader_unindexed(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_signal_mediainfo_reader_unindexed(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static string xmmsc_userconfdir_get(string buf, int len) {
    string ret = XmmsClientInterfacePINVOKE.xmmsc_userconfdir_get(buf, len);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_select(SWIGTYPE_p_xmmsc_connection_St conn, string query) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_select(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), query);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlist_save_current(SWIGTYPE_p_xmmsc_connection_St conn, string name) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlist_save_current(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), name);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlist_load(SWIGTYPE_p_xmmsc_connection_St conn, string name) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlist_load(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), name);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_add_entry(SWIGTYPE_p_xmmsc_connection_St conn, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_add_entry(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_add_entry_args(SWIGTYPE_p_xmmsc_connection_St conn, string url, int numargs, SWIGTYPE_p_p_char args) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_add_entry_args(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), url, numargs, SWIGTYPE_p_p_char.getCPtr(args));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_add_entry_encoded(SWIGTYPE_p_xmmsc_connection_St conn, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_add_entry_encoded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_get_info(SWIGTYPE_p_xmmsc_connection_St arg0, SWIGTYPE_p_uint32_t arg1) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_get_info(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0), SWIGTYPE_p_uint32_t.getCPtr(arg1));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_add_to_playlist(SWIGTYPE_p_xmmsc_connection_St c, string query) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_add_to_playlist(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), query);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlists_list(SWIGTYPE_p_xmmsc_connection_St arg0) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlists_list(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlist_list(SWIGTYPE_p_xmmsc_connection_St arg0, string playlist) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlist_list(SWIGTYPE_p_xmmsc_connection_St.getCPtr(arg0), playlist);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlist_import(SWIGTYPE_p_xmmsc_connection_St conn, string playlist, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlist_import(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), playlist, url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlist_export(SWIGTYPE_p_xmmsc_connection_St conn, string playlist, string mime) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlist_export(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), playlist, mime);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_playlist_remove(SWIGTYPE_p_xmmsc_connection_St conn, string playlist) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_playlist_remove(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), playlist);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_path_import(SWIGTYPE_p_xmmsc_connection_St conn, string path) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_path_import(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), path);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_path_import_encoded(SWIGTYPE_p_xmmsc_connection_St conn, string path) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_path_import_encoded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), path);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_rehash(SWIGTYPE_p_xmmsc_connection_St conn, SWIGTYPE_p_uint32_t id) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_rehash(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), SWIGTYPE_p_uint32_t.getCPtr(id));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_get_id(SWIGTYPE_p_xmmsc_connection_St conn, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_get_id(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_remove_entry(SWIGTYPE_p_xmmsc_connection_St conn, SWIGTYPE_p_uint32_t entry) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_remove_entry(SWIGTYPE_p_xmmsc_connection_St.getCPtr(conn), SWIGTYPE_p_uint32_t.getCPtr(entry));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_entry_property_set_int(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id, string key, SWIGTYPE_p_int32_t value) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_entry_property_set_int(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id), key, SWIGTYPE_p_int32_t.getCPtr(value));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_entry_property_set_int_with_source(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id, string source, string key, SWIGTYPE_p_int32_t value) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_entry_property_set_int_with_source(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id), source, key, SWIGTYPE_p_int32_t.getCPtr(value));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_entry_property_set_str(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id, string key, string value) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_entry_property_set_str(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id), key, value);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_entry_property_set_str_with_source(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id, string source, string key, string value) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_entry_property_set_str_with_source(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id), source, key, value);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_entry_property_remove(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id, string key) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_entry_property_remove(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id), key);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_medialib_entry_property_remove_with_source(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_uint32_t id, string source, string key) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_medialib_entry_property_remove_with_source(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_uint32_t.getCPtr(id), source, key);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    if (XmmsClientInterfacePINVOKE.SWIGPendingException.Pending) throw XmmsClientInterfacePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_xform_media_browse(SWIGTYPE_p_xmmsc_connection_St c, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_xform_media_browse(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_xform_media_browse_encoded(SWIGTYPE_p_xmmsc_connection_St c, string url) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_xform_media_browse_encoded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), url);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_bindata_add(SWIGTYPE_p_xmmsc_connection_St c, SWIGTYPE_p_unsigned_char data, uint len) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_bindata_add(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), SWIGTYPE_p_unsigned_char.getCPtr(data), len);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_bindata_retrieve(SWIGTYPE_p_xmmsc_connection_St c, string hash) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_bindata_retrieve(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), hash);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_bindata_remove(SWIGTYPE_p_xmmsc_connection_St c, string hash) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_bindata_remove(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c), hash);
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_medialib_entry_changed(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_medialib_entry_changed(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_medialib_entry_added(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_medialib_entry_added(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_broadcast_medialib_playlist_loaded(SWIGTYPE_p_xmmsc_connection_St c) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_broadcast_medialib_playlist_loaded(SWIGTYPE_p_xmmsc_connection_St.getCPtr(c));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_xmmsc_result_St xmmsc_result_restart(SWIGTYPE_p_xmmsc_result_St res) {
    IntPtr cPtr = XmmsClientInterfacePINVOKE.xmmsc_result_restart(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    SWIGTYPE_p_xmmsc_result_St ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_xmmsc_result_St(cPtr, false);
    return ret;
  }

  public static void xmmsc_result_run(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_xmms_ipc_msg_t msg) {
    XmmsClientInterfacePINVOKE.xmmsc_result_run(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_xmms_ipc_msg_t.getCPtr(msg));
  }

  public static xmmsc_result_type_t xmmsc_result_get_class(SWIGTYPE_p_xmmsc_result_St res) {
    xmmsc_result_type_t ret = (xmmsc_result_type_t)XmmsClientInterfacePINVOKE.xmmsc_result_get_class(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static void xmmsc_result_disconnect(SWIGTYPE_p_xmmsc_result_St res) {
    XmmsClientInterfacePINVOKE.xmmsc_result_disconnect(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
  }

  public static void xmmsc_result_ref(SWIGTYPE_p_xmmsc_result_St res) {
    XmmsClientInterfacePINVOKE.xmmsc_result_ref(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
  }

  public static void xmmsc_result_unref(SWIGTYPE_p_xmmsc_result_St res) {
    XmmsClientInterfacePINVOKE.xmmsc_result_unref(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
  }

  public static void xmmsc_result_notifier_set(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_f_p_struct_xmmsc_result_St_p_void__void func, SWIGTYPE_p_void user_data) {
    XmmsClientInterfacePINVOKE.xmmsc_result_notifier_set(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_f_p_struct_xmmsc_result_St_p_void__void.getCPtr(func), SWIGTYPE_p_void.getCPtr(user_data));
  }

  public static void xmmsc_result_wait(SWIGTYPE_p_xmmsc_result_St res) {
    XmmsClientInterfacePINVOKE.xmmsc_result_wait(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
  }

  public static int xmmsc_result_iserror(SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_iserror(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static string xmmsc_result_get_error(SWIGTYPE_p_xmmsc_result_St res) {
    string ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_error(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static int xmmsc_result_get_int(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_int r) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_int(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_int.getCPtr(r));
    return ret;
  }

  public static int xmmsc_result_get_uint(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_uint32_t r) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_uint(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_uint32_t.getCPtr(r));
    return ret;
  }

  public static int xmmsc_result_get_string(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_p_char r) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_string(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_p_char.getCPtr(r));
    return ret;
  }

  public static int xmmsc_result_get_bin(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_p_unsigned_char r, SWIGTYPE_p_unsigned_int rlen) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_bin(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_p_unsigned_char.getCPtr(r), SWIGTYPE_p_unsigned_int.getCPtr(rlen));
    return ret;
  }

  public static xmmsc_result_value_type_t xmmsc_result_get_dict_entry_type(SWIGTYPE_p_xmmsc_result_St res, string key) {
    xmmsc_result_value_type_t ret = (xmmsc_result_value_type_t)XmmsClientInterfacePINVOKE.xmmsc_result_get_dict_entry_type(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), key);
    return ret;
  }

  public static int xmmsc_result_get_dict_entry_str(SWIGTYPE_p_xmmsc_result_St res, string key, SWIGTYPE_p_p_char r) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_dict_entry_str(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), key, SWIGTYPE_p_p_char.getCPtr(r));
    return ret;
  }

  public static int xmmsc_result_get_dict_entry_int32(SWIGTYPE_p_xmmsc_result_St res, string key, SWIGTYPE_p_int32_t r) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_dict_entry_int32(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), key, SWIGTYPE_p_int32_t.getCPtr(r));
    return ret;
  }

  public static int xmmsc_result_get_dict_entry_uint32(SWIGTYPE_p_xmmsc_result_St res, string key, SWIGTYPE_p_uint32_t r) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_dict_entry_uint32(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), key, SWIGTYPE_p_uint32_t.getCPtr(r));
    return ret;
  }

  public static int xmmsc_result_dict_foreach(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_f_p_q_const__void_enum_xmmsc_result_value_type_t_p_q_const__void_p_void__void func, SWIGTYPE_p_void user_data) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_dict_foreach(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_f_p_q_const__void_enum_xmmsc_result_value_type_t_p_q_const__void_p_void__void.getCPtr(func), SWIGTYPE_p_void.getCPtr(user_data));
    return ret;
  }

  public static int xmmsc_result_propdict_foreach(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_f_p_q_const__void_enum_xmmsc_result_value_type_t_p_q_const__void_p_q_const__char_p_void__void func, SWIGTYPE_p_void user_data) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_propdict_foreach(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_f_p_q_const__void_enum_xmmsc_result_value_type_t_p_q_const__void_p_q_const__char_p_void__void.getCPtr(func), SWIGTYPE_p_void.getCPtr(user_data));
    return ret;
  }

  public static void xmmsc_result_source_preference_set(SWIGTYPE_p_xmmsc_result_St res, SWIGTYPE_p_p_char preference) {
    XmmsClientInterfacePINVOKE.xmmsc_result_source_preference_set(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), SWIGTYPE_p_p_char.getCPtr(preference));
  }

  public static int xmmsc_result_is_list(SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_is_list(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static int xmmsc_result_list_next(SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_list_next(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static int xmmsc_result_list_first(SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_list_first(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static int xmmsc_result_list_valid(SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_list_valid(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static int xmmsc_result_get_type(SWIGTYPE_p_xmmsc_result_St res) {
    int ret = XmmsClientInterfacePINVOKE.xmmsc_result_get_type(SWIGTYPE_p_xmmsc_result_St.getCPtr(res));
    return ret;
  }

  public static string xmmsc_result_decode_url(SWIGTYPE_p_xmmsc_result_St res, string arg1) {
    string ret = XmmsClientInterfacePINVOKE.xmmsc_result_decode_url(SWIGTYPE_p_xmmsc_result_St.getCPtr(res), arg1);
    return ret;
  }

}
