/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum xmms_playback_status_t {
  XMMS_PLAYBACK_STATUS_STOP,
  XMMS_PLAYBACK_STATUS_PLAY,
  XMMS_PLAYBACK_STATUS_PAUSE
}
