/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum xmms_plugin_type_t {
  XMMS_PLUGIN_TYPE_ALL,
  XMMS_PLUGIN_TYPE_OUTPUT,
  XMMS_PLUGIN_TYPE_PLAYLIST,
  XMMS_PLUGIN_TYPE_EFFECT,
  XMMS_PLUGIN_TYPE_XFORM
}
